
[features]
seeds = false
skip-lint = false

[programs.devnet]
amm = "HHmUttCbE4eC3a98VH2o7gGG8yFNHtdeeuMBaa8M3aae"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/mnt/f/Solana_Keypair/payer.json"

[scripts]
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/create-amm.ts"
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/create-pool.ts"
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/deposit-liquidity.ts"

# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/swap.ts"

test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/withdraw_liquidity.ts"